## 환경설정

API KEY 를 설정합니다.

In [2]:
# API 키를 환경변수로 관리하기 위한 설정 파일
from dotenv import load_dotenv

# API 키 정보 로드
load_dotenv()

True

LangChain으로 구축한 애플리케이션은 여러 단계에 걸쳐 LLM 호출을 여러 번 사용하게 됩니다. 이러한 애플리케이션이 점점 더 복잡해짐에 따라, 체인이나 에이전트 내부에서 정확히 무슨 일이 일어나고 있는지 조사할 수 있는 능력이 매우 중요해집니다. 이를 위한 최선의 방법은 [LangSmith](https://smith.langchain.com)를 사용하는 것입니다.

LangSmith가 필수는 아니지만, 유용합니다. LangSmith를 사용하고 싶다면, 위의 링크에서 가입한 후, 로깅 추적을 시작하기 위해 환경 변수를 설정해야 합니다.

## 모듈별로 자세히 살펴보기

In [3]:
import bs4
from langchain import hub
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import WebBaseLoader
from langchain_community.vectorstores import Chroma, FAISS
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

USER_AGENT environment variable not set, consider setting it to identify your requests.

아래는 [](https://teddylee777.github.io/langchain/rag-naver-news-qa/) 에서 다뤘던 기본적인 RAG 모델을 사용하는 예제입니다.

여기서 각 단계별로 다양한 옵션을 설정하거나 새로운 기법을 적용할 수 있습니다.

In [5]:
# 단계 1: 문서 로드(Load Documents)
# 뉴스기사 내용을 로드하고, 청크로 나누고, 인덱싱합니다.
url = "https://n.news.naver.com/article/437/0000378416"
loader = WebBaseLoader(
    web_paths=(url,),
    bs_kwargs=dict(
        parse_only=bs4.SoupStrainer(
            "div",
            attrs={"class": ["newsct_article _article_body", "media_end_head_title"]},
        )
    ),
)
docs = loader.load()


# 단계 2: 문서 분할(Split Documents)
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=50)

splits = text_splitter.split_documents(docs)

# 단계 3: 임베딩 & 벡터스토어 생성(Create Vectorstore)
# 벡터스토어를 생성합니다.
vectorstore = FAISS.from_documents(documents=splits, embedding=OpenAIEmbeddings())

# 단계 4: 검색(Search)
# 뉴스에 포함되어 있는 정보를 검색하고 생성합니다.
retriever = vectorstore.as_retriever()

# 단계 5: 프롬프트 생성(Create Prompt)
# 프롬프트를 생성합니다.
prompt = hub.pull("rlm/rag-prompt")

# 단계 6: 언어모델 생성(Create LLM)
# 모델(LLM) 을 생성합니다.
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)


def format_docs(docs):
    # 검색한 문서 결과를 하나의 문단으로 합쳐줍니다.
    return "\n\n".join(doc.page_content for doc in docs)


# 단계 7: 체인 생성(Create Chain)
rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

# 단계 8: 체인 실행(Run Chain)
# 문서에 대한 질의를 입력하고, 답변을 출력합니다.
question = "부영그룹의 출산 장려 정책에 대해 설명해주세요"
response = rag_chain.invoke(question)

# 결과 출력
print(f"URL: {url}")
print(f"문서의 수: {len(docs)}")
print("===" * 20)
print(f"[HUMAN]\n{question}\n")
print(f"[AI]\n{response}")

ImportError: Could not import faiss python package. Please install it with `pip install faiss-gpu` (for CUDA supported GPU) or `pip install faiss-cpu` (depending on Python version).

## 단계 1: 문서 로드(Load Documents)

- [공식문서 링크 - Document loaders](https://python.langchain.com/docs/modules/data_connection/document_loaders/)

In [5]:
import json
import pandas as pd
from datetime import datetime

with open ("instagram_diary/content/posts_1.json", "r") as f:
    data = json.load(f)

# DataFrame 생성
df = pd.DataFrame()
for i in range(len(data)):
    df = pd.concat([df,pd.DataFrame(data[i])])

# 유니코드 이스케이프 시퀀스를 디코딩
df = df.map(lambda x: x.encode('latin-1').decode('utf-8') if isinstance(x, str) else x)
df = df.reset_index(drop=True)

#  전처리 


# df = df.copy()
df.loc[df.title.isna(),'creation_timestamp']= [x.get('creation_timestamp') for x in df.loc[df.title.isna()]['media']]
df.loc[df.title.isna(),'title']= [x.get('title').encode('latin-1').decode('utf-8') for x in df.loc[df.title.isna()]['media']]
df['dt'] = [datetime.fromtimestamp(x) for x in df['creation_timestamp']]

# 결과 출력
print(df.shape)
df.head()

(4455, 4)

,media,title,creation_timestamp,dt
0,{'uri': 'media/posts/202407/451325293_83729456...,"인도네시아로 떠나버린 엄마와 영종도로 떠나버린 언니,,,아침부터 아주 시끌벅적 난리...",1.721013e+09,2024-07-15 12:17:39
1,{'uri': 'media/posts/202407/450766642_98856626...,"인도네시아로 떠나버린 엄마와 영종도로 떠나버린 언니,,,아침부터 아주 시끌벅적 난리...",1.721013e+09,2024-07-15 12:17:39
2,{'uri': 'media/posts/202407/451295091_12016493...,"인도네시아로 떠나버린 엄마와 영종도로 떠나버린 언니,,,아침부터 아주 시끌벅적 난리...",1.721013e+09,2024-07-15 12:17:39
3,{'uri': 'media/posts/202407/451268789_47500573...,"인도네시아로 떠나버린 엄마와 영종도로 떠나버린 언니,,,아침부터 아주 시끌벅적 난리...",1.721013e+09,2024-07-15 12:17:39
4,{'uri': 'media/posts/202407/451422413_45867830...,"인도네시아로 떠나버린 엄마와 영종도로 떠나버린 언니,,,아침부터 아주 시끌벅적 난리...",1.721013e+09,2024-07-15 12:17:39

In [6]:
df_nodup = df[["title", 'dt']].drop_duplicates(keep='last')
print(df_nodup.shape)
df_nodup.head()

(1449, 2)

                                                title                  dt
4   인도네시아로 떠나버린 엄마와 영종도로 떠나버린 언니,,,아침부터 아주 시끌벅적 난리... 2024-07-15 12:17:39
5   아니 오늘 사진 이거 밖에 없어? 근데 오늘 정말 웃기는 하루ㅋㅋㅋ 아침에 만나서 ... 2024-07-13 23:56:29
8   퇴근하구 오빠랑 양재에서 술막엇다. 출근해서 왠지모르게 자꾸 맛잇는가 먹고싶은 날이... 2024-07-13 01:56:38
13  오늘 요약 재밋엇음 은근 사람만나는것도 재밋네 혼자 노는것도 물론 재밋긴한데.ㅋㅋㅋ... 2024-07-11 23:39:17
18  ㅎㅏ 별개로 누님과의 만남은 즐거웠움 김유환 호감도-100 김은수 호감도+10000... 2024-07-11 00:11:55

In [11]:
from langchain_community.document_loaders import DataFrameLoader
# DataFrame에서 데이터를 로드하고, 'Team' 열을 페이지 내용으로 사용합니다.
loader = DataFrameLoader(df_nodup, page_content_column="title")

docs = loader.load()  # 데이터를 로드합니다.
print(f"문서의 수: {len(docs)}\n")

# 10번째 페이지의 내용 출력
print(f"\n[페이지내용]\n{docs[1400].page_content[:500]}")
print(f"\n[metadata]\n{docs[1400].metadata}\n")

문서의 수: 1449


[페이지내용]
마음에 들었다 슬랙스!

[metadata]
{'dt': Timestamp('2016-05-06 15:42:46')}

---

## 단계 2: 문서 분할(Split Documents)

### RecursiveTextSplitter

이 텍스트 분할기는 일반 텍스트에 권장되는 텍스트 분할기입니다.

1. 텍스트가 어떻게 분할 규칙: list of `separators`
2. 청크 크기가 어떻게 측정되는가: `len` of characters

In [15]:
# langchain 패키지에서 RecursiveCharacterTextSplitter 클래스를 가져옵니다.
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.text_splitter import CharacterTextSplitter

`RecursiveCharacterTextSplitter` 클래스는 텍스트를 재귀적으로 분할하는 기능을 제공합니다. 이 클래스는 `chunk_size`로 분할할 청크의 크기, `chunk_overlap`으로 인접 청크 간의 겹침 크기, `length_function`으로 청크의 길이를 계산하는 함수, 그리고 `is_separator_regex`로 구분자가 정규 표현식인지 여부를 지정하는 매개변수를 받습니다. 예시에서는 청크 크기를 100, 겹침 크기를 20으로 설정하고, 길이 계산 함수로 `len`을 사용하며, 구분자가 정규 표현식이 아님을 나타내기 위해 `is_separator_regex`를 `False`로 설정합니다.

In [13]:
recursive_text_splitter = RecursiveCharacterTextSplitter(
    # 정말 작은 청크 크기를 설정합니다.
    chunk_size=100,
    chunk_overlap=10,
    length_function=len,
    is_separator_regex=False,
)

In [16]:
character_text_splitter = CharacterTextSplitter(
    chunk_size=100, chunk_overlap=10, separator=" "
)
for sent in character_text_splitter.split_documents(docs):
    print(sent)
print("===" * 20)
recursive_text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=100, chunk_overlap=10
)
for sent in recursive_text_splitter.split_documents(docs):
    print(sent)

page_content='인도네시아로 떠나버린 엄마와 영종도로 떠나버린 언니,,,아침부터 아주 시끌벅적 난리엿다 겨우 엄마랑 인사하고 쉬즈곤. 잘다녀오세용~그래서 갑자기 결정된 오빠 우리집' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='결정된 오빠 우리집 놀러오기~~~오빠가 아침부터 와줘서 점심도 까르보나라 해줫다. 웃겼던건 오빠 치즈 열심히 다지고 잇엇는데 내가 강판으로 갈아버리기ㅠ미안해 난오빠가 강판' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='난오빠가 강판 싫어하는줄 알았어,,,오늘도 역시 레전드 맛잇는 까르보나라^____^* 행복해랏~~~ 김유환 내가 까르보나라 잘하는 거 같으니까 은근히 서운해하는게' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='은근히 서운해하는게 웃기다ㅋㅋㅋㅋㅋㅋㅋㅋㅋ하지만 오빠가 해주는게 젤로 맛잇다고요~~~^___^* 나는 옆에서 오빠 요리 보조햇다. 그냥 옆에서 이거저거 치워주기 그러고 아 들어오기' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='그러고 아 들어오기 전에 마트에서 오겹살 사서 에어프라이어에 구웟다ㅋㅋㅋㅋㅋ어떻게 이런 멋진 생각을! 아주 조은 생각이야 근데 좀 많앗다. 아 밥먹으면서 푸른산호초 부르는 하니에' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='부르는 하니에 빠져서 뉴진스를 진짜 무한반복해서 영상봄 첨엔 너무 예쁘고 귀엽고 즐겁고 재밌었는데 김유환이 내가 뉴진스 예쁘다고 하는 말에 동조하자마자 재미없어짐. 보다가 점점' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='보다가 점점 지겨워짐 이러다가 김유환 입덕하겟다 난 연예인 덕질같은 건 옆에서 즐겁게 봐줄 자신이 없다....차라리 2D 덕질이 나을거 같아...그래서 이영지 영상 틀엇는데 세상' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='영상 틀엇는데 세상 시끄러워서 내가 계속 시끄럽다고 해서 음량을 엄청 줄엿는데 엄청 줄엿는데도 계속 시끄러워 음량이랑 상관없이ㅋㅋㅋㅋㅋ이게 대체. ㅓ람...그러다가 그냥 거의 오빠' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='그냥 거의 오빠 위에 누워서 낮잠자버렷다. 둘이 아주 잘잠 ^.^ 뒤늦게 일어나서 아우 배불러 하면서 해피아워 보내구~~~오빠가 우리 횟수 줄엇다고 해서 화들짝 놀람 그냥 내가' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='놀람 그냥 내가 아파서 그런거 아니엇나? 아니엇어!?!?!?! 근데 요즘 좀 잠을 많이 자긴 햇어. 여튼 그러구 이케아 놀러 나가기. 근데 생각보다? 이케아? 가서 이거 사고 싶고' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='이거 사고 싶고 저거 사고 싶고 그런게 없엇다. 새집은 아니지만 그래도 내방이라는게 잇으니까 나도 내방이 꾸미고 싶을 수도 잇엇는데?? 하나도 관심이 안생겨 ;; 어쩌지 나중에' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content=';; 어쩌지 나중에 집생기면 꾸미는 일이 즐겁지 않고 할일1로 생각되면 어쩌지 좀 괴로울듯 근데 나 걍 수납공간만 잘되어잇으면 대충 살아도 될거 같기도 함. 근데 유리수납장은' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='근데 유리수납장은 시렁ㅋㅎ 내 집이 잇엇더라면 구조를 생각하고 이건 이렇게 저건 저렇게 하는게 생각날텐데 또 그러지도 않아서 좀 의외였음. 이번 만남은 또 왜그런지 모르겟지만' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='왜그런지 모르겟지만 유환이와의 결혼을 계속 상상하게 되엇다. 아 집에 잇어서 그랫나? 완전 게으르게 맨날 맛잇는거 먹고 낮잠자는 삶 살게 되는거 아니야? 근데 좀 위험해 이렇게' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='좀 위험해 이렇게 좋기만 한 상황에서 결혼을 결정하는건 합리적이지 않아ㅠ 원래 연애초는 행복하고 좋은 일만 가득한거라고,,,이런 일반적이지 않은 상황에서 결정하는게 먼가 걸린다.' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='먼가 걸린다. 라고 생각하고 있었는데 오빠는 혹시 자기가 개선했으면 하는 사항이 잇냐고 물어봣다. 왜?!?!?!? 내가 뭐가 걸리는게 잇어서 결혼을 자꾸 미루는거' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='자꾸 미루는거 같아서!??!?!?!?! 햇더니 맞대 그거 아니야!!!!!!!!!!!!!!!!!! 그냥 이렇게 행복하고 좋기만한 상황말고 좀 더 일반적인 상황도 보고싶은거 뿐이야' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='보고싶은거 뿐이야 근데 사실 그건 1년으로는 택도 없을거 같긴함 한. 3-4년은 봐야하는거 같은데 우리에겐 그정도 시간은 없는거자낳ㅠ 여튼 이런저런 생각하기. 저녁은 피자' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='저녁은 피자 시켜먹기.

아맞다 그리고 이케아는 엄청 엄청 쾌적하진 않앗음 약간 더움. 유환이 약간 불행해지는거 포착. 거기에서 오는 길에 약간 출출해져서 초밥먹고 싶었는데?' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='초밥먹고 싶었는데? 후스시를 갈것인가 아트스시를 갈것인가 내가 고민하는 동안 유환이가 내 결정을 도와주려다가ㅋㅋㅋㅋ지도를 못봐서 길 잘못들엇다 근데 길잘못드니까ㅋㅋㅋㅋ40분 늘어남' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='늘어남 30분인가?ㅋㅋㅋㅋㅋㅋㅋㅋㅋ그때 양재에서 말도안돼...가 생각나서 너무 웃겻다. 그래도 먼가 드라이브하는 느낌나고 하늘도 예쁘고 좋앗다. 아주 배고픈 상태도 아니고~그래서' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='아니고~그래서 구냥 집에 즐겁게 가서 잭슨피자나 먹기. 하와이안 먹고 싶엇는데 결국 먹어서 기쁜 나. 유한ㅇ니는 그냥 한조각만 먹고 안먹엇는데 왠지 모르지만 서운해 맛잇게' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='서운해 맛잇게 먹어줫으면 좋겟어ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ왜...내가 조아하는걸 안조아해.....?!?!?!?!?!?!?!?!??!? 우리 한몸아니엇어...????????? 강요하기.' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='강요하기. 이러쿵저러쿵 하이볼도 해먹구 과자도 먹구 인사이드아웃 보면서 스트레칭도 하고 잠들기^.^ 인이가 너무 심하게 울어서 새벽에 좀 깼지만 그래두 엄청 덥지는 않앗다 다행.' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='않앗다 다행. 유환이 잠 잘. 못잤을거 같아서 조금 걱정,,,,' metadata={'dt': Timestamp('2024-07-15 12:17:39')}
page_content='아니 오늘 사진 이거 밖에 없어? 근데 오늘 정말 웃기는 하루ㅋㅋㅋ 아침에 만나서 골드리버가서 내내 자다가 나왓다. ㄹㅇ 잠만 잔하루ㅌㅋㅋㅋ가서~~해피아워 호로록 보내구😋 와 근데' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='보내구😋 와 근데 진짜 조앗다 유환이는 정말 완뱍해. 그러고 배달로 닭강정 같이 받으러 갓다가~맛은 없었지마는~~그러고 태계일주보다가 잠들어서 거의 네시간은 잔 것 같다. 시간 다' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='것 같다. 시간 다 지나서 일어나따. 그애서 어디가쥥..하다가 샤브샤브로 메뉴정하고 공덕으로 출발.@등촌 샤브사브@진짜 조은 선택이엇다 오빠 집에 주차해두고 등촌 갓는데 웬걸 너무' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='갓는데 웬걸 너무 깔끔하고 냄새도 안베고 너무 맛잇엇다 쾌락-천국이다 감탄하며 먹엇다ㅎㅅㅎ 그러고 배불러 죽겟지만 꽈배기 사먹구오빠는 소금빵+커피사먹구 한강으러 이동. 가서' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='이동. 가서 이러쿵저러쿵 노래들으면서 시티팝듣다가ㅋㅋㅋㅋ아맞다 내폰이ㅋㅋㅋㅋ공덕가는길에 내폰이 블루투스에 연걀됏는데 오빠가 막 안절부절못하면서 자구 자기걸로 바꾸려고 햇다' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='바꾸려고 햇다 어이없어ㅋㅋㅋㅋㅋ진짜 말그대로 안절부절. 자꾸 상황을 본인이 컨트롤하고 싶어하는 경향이 있는데 내가 혹시 당신 통제광이냐고 놀리고 ㅋㅋㅋ오빠는 자기는 역치가 높다길래' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='역치가 높다길래 뭔 역치가 높냐 오빠는 지금 블류투스 연결된것도 못참는데 하면서 막 놀렷다 너무 재밋어 그래서 내가 자기객관화를 좀하자고 오빠는 통제성향이다 역치도 안높다 하니까' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='안높다 하니까 알겟다고 웃엇다ㅋㅋㅋㅋㅋㅋㅋㅋ레고때도 내가ㅋㅋㅋ각안맞춰서 하는게 못마땅해서엿어ㅋㅋㅋㅋㅋㅋ정말 웃기는 사람이야 그렇다고 뺏어갈 일이냐고ㅠㅠㅋㅋㅋㅋㅋ정말웃겨. 오빠랑' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='오빠랑 잇으면 재밋고 즐겁고 행복하고 편안하고 너무 좋당🥰 또 쓰다보니까 보고싶넹 하루종일 같이 낮잠자구~~~오빠는 푹신하고 따듯해서 조아. 오빠가 내가 왜조아?해서 따둣해서' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='따둣해서 좋다고 하니까 그러면 그냥 난로사주겟다고 툴툴대는데 귀여워. 난로사줘도 난로 안써 유환이부터 찾을거야!!! 근데 진짜 짱피곤햇는지 어케 둘다 그렇게 내내 잤지? 잘잣다.' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='잤지? 잘잣다. 오늘은 결혼해서 같이 잇는게 좋겟다는 생각이 꽤나 많이 드는 하루엿음 오빠는 내가 내년에 걀혼해도 좋겟다는 생각이 점점 들고 잇다는걸 알고잇다고 나는 윤영이에 대해' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='나는 윤영이에 대해 잘알아 라고 햇다 그래서 당신이 뭘알아? 햇지만 잘아네~*^.^* 아니 하고 싶은 마음이 점점 더 커지고 같이 잇는 시간을 좀 더 에너지를 덜쓰고 만날 수' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='덜쓰고 만날 수 잇으면 좋겟더고 생각은 하지만 그래도 내년은 좀 빨라..우리 유목민같다는 말이 너무 웃겻다 유목민이라니ㅠㅠ정착해야되는데 ㅠㅠ사람은 땅에 발붙이고 살아야하는데ㅠ' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='살아야하는데ㅠ 보고시푼 유환이. 하지만 난 돈이 별루 없는데ㅠㅠ😭나는 요만큼 가져오는데 유환이는 이만큼 가져오잖아ㅠㅠ😭 별생각없엇는데 갑자기 요런 새로운 걱정이 생기는' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='걱정이 생기는 요즘

아맞다 그러고 한강가서 푸른산호초를 끝도없이 들으며ㅋㅋㅋㅋ하니 너무 ㄱ엽고 마츠다세이코도 보고 반포쪽도 걷고왓다. 아 그@게임 다운 받아봐야징. 산책조아' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='산책조아 오빠랑 산책하는거 정말@조아 오빠가 같이 뛰고싶어햇지만 난 뛰고싶지않아 너무 더운걸 ㅠㅠ 걷는건 조아 유환이는 왜이엏게 좋을까? 구냥 앉아서 뽀뽀만햐도 좋당. 어쩌다보니' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='좋당. 어쩌다보니 또 해피아워보내기 근데 또 너무 좋앗다. 왜이렇게 좋을까 오빠가 이거만 가지고도 결혼할 수 잇겟다고 했다ㅋㅋㅋㅋㅋ오빠도 조은거 맞지..?? 보고싶당 유환이 낼' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='보고싶당 유환이 낼 언니랑 엄마 둘다 빠이하구 오빠랑 놀아야징 룰루랄ㄹ라' metadata={'dt': Timestamp('2024-07-13 23:56:29')}
page_content='퇴근하구 오빠랑 양재에서 술막엇다. 출근해서 왠지모르게 자꾸 맛잇는가 먹고싶은 날이엇는데 공화춘 먹고싶다고 징징대다가 워니랑 같이 샤브샤브먹기루함. 맛잇엇다. 잘먹고 일 잘하다가' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='잘먹고 일 잘하다가 티탐하구 오빠보기*^.^* 양재에서 고기먹으러갓는데 테라가 아주 기가막햐 어떻개 그렇게 시원힌 맥주가…!!!!!! 진짜 너무 맛잇어서 세병째먹고' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='맛잇어서 세병째먹고 오겹2돼지갈비2까지 배터지게 먹고 2차기서 또 술 엄청 먹엇다. 모둠꼬치+생맥/하이볼+사케2도쿠리🧐엄청 먹엇다 매우 취해ㅛ다 그러고 두시간동안 암걸리먄' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='두시간동안 암걸리먄 상대한ㅌㅔ 맣할것인가 말하지 않를것인가 가지고 얘기해ㅛ다 ㅋㅋㅋㅋㅋㅋㅋㅋ진짜 뭔 이상한 주제로ㅋㅋㅋㅋㅋ두시간이나ㅋㅋ나는 말안해준다니까 오빠가 서운해햇다 하지만' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='서운해햇다 하지만 시른걸? 내맘리야 해ㅛ지만 오빠 끊임없이 설득하기 두시간 설득해서 말해주겟다는 손각서 썻다. 오빠는 그걸 알게하고 선택할 수 있게 하는게 상대에 대한 배려라고' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='대한 배려라고 생각한다고 햇다. 난ㅋㅋㅋㅋ그런 애초에 배려아니라고 생각해 알려쥬는 순간 그걸 미안 난 못버틸같아하고 떠나면 거기에 따르는 죄책감은 어떡함ㅠ잘못도 아닌데 아픈 사람' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='아닌데 아픈 사람 버리는 사람이 되어버린 죄책감 아픈 사람한테도 상처 안아픈 사람에게도 마음의 짐 그랗다고 같이 이겨내보겟가고 홋은 마지막 함께하게ㅛ다고 남으면 그 힘든 시간의' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='그 힘든 시간의 모습을 또 보여쥬고 마지막기억이 아픈 모습이라는거ㅛ도 너무 싫고 상대도 힘들고 오우 다시생각히도 싫다;; 걍 건강하지만 나쁜사람이엇다고 기억남고 싶다. 그리고' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='싶다. 그리고 나아중에 알게된다고 하더라도 그땐 시간이 지낫으니 그런가하고 넘어가겟지. 주변인이 죽는건 아무리봐도 몇년안에 극복하기 쉬울거 같지않다 반대로 오빠가 암걸리면 당연히' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='암걸리면 당연히 말해쥬ㅓㅆ우면 좋겟고 마지막을 함께하고 싶고 같이 정리하고 싶지만 오빠떠나고 나몀 솔직히 혼자 제정신으로 못살거같다 극복? 못할듯 평생 못잊고 생각날듯 진짜' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='생각날듯 진짜 극복못할거같다 그러면서 우중이 생각이 계솟 낫는데 아 그때 그거 대답해줄걸 그때 걔혼자 걸어갈때 가서 인사할걸 하고 그게ㅋㅋㅋ10년이 넘었는데도 아직도 생각난다' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='아직도 생각난다 그리고 걔는 아직도 내기억속엔 고등학생이고 그 이후는 근황이 없다는게 아직도 너무 낯설다. 근데 김유환이 죽는다????? 와 절대 극복못해 진심으로…시한부면 그' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='그 시간안에 마음정리같은거도 절대 못한다 솔직히 몇년이 있어도 마음정리 못해 쓰다가 갑자기 ㄴ눈물남 힝ㅠ유환아 죽지마ㅠ절대죽으면 안돼 유환이 조건부 불사됏으몀 좋겟다 나보다' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='좋겟다 나보다 하루더살고 가 불로는 안됨 같이 늙어야돼ㅠㅠ여튼 유환이한테 알렺 기싫어. 약속햇지만 알려주기싫음. 싫어!!! 근데 그런일 안일어나길. 차라리 나쁘게 헤어지면 빠르게' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='헤어지면 빠르게 극복하고 나아가려고 할텐데 아픔+죽음 서사는 자꾸 뒤돌아보게될거같아 그러고보니 유환이는 전여친도 그 멈가 상황 힘들엇던 전여친이 젤@아픈 연애랫어 갑자기' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='연애랫어 갑자기 눈물쏙들어감 갑자기 빡친다 유환이의 연애관련 가장 아련한 연애 1위가 내가 아니라니 가장 빡치는@연애1위 이런거는@아니거 싶지만 저런 가장 아픈 연애라니 먼가' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='아픈 연애라니 먼가 아련해서 짱나네 저 아련한 순위를 나로 갱신시키고 싶은데 우린 아플일이 없어 그리거 유환이는 안아팟으면 좋겟어 유환이 뮤병불사야

ㅇ아 그러고 내가 결혼하면' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='내가 결혼하면 당연히 알려주지 보호자잖아 그리고 그런 힘든일이잇을때 옆에 있겟다고 서약하는게 결혼이니까 그건 의무이자 권리가 되는거지만 결혼 전엔 아니라구 햇더니 유환 서운해하며' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='유환 서운해하며 자기는 그 법적권리가 갖고 싶다고 햇다 자기가 이번 일본여행가서 큰릴이 나더라도 자기가 할 스 잇는건 한국에잇는 가졷들한테 연락하는게 다아니냐며 불만수러워햇다' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='불만수러워햇다 연애할때는 그런 권리가 없고 결혼흐면 생긴다는 것에 너무 불만스러워하고 지금 당장 그 권리릉 얻고싶어함 결혼은 한낯 서류일뿐이고 나와 오빠의 관계는 똑같은데 왜 결혼' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='똑같은데 왜 결혼 이후에만 그런 암걸림 알림에 대한 권리가 생기는거냐며 내 보호자가 되고싶다고;;; 근데 이게 대체 무슨 마음이야? 잘 이해는 안간다 왜 저렇게 저 권리를' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='저렇게 저 권리를 갖고싶어하는거야 권리라기보다는 책임에 가까운거 같은데;; 책임같은거 안지우겟다는데!! 여튼 좀 웃기는 대화 그러다가 유환의 작누만낫을때 오빠가 오빠네가족의 리더는' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='오빠네가족의 리더는 아부지시고 오빠가 결혼하면 그 가족의 리더는 자기라고ㅋㅋㅋ한게ㅋㅋㅋ또 생각남 우리집 리더가 오빠라고 누가그랫어? 나일수도 있잖아?😋✌️왜 저렇게 책임지고' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='저렇게 책임지고 보호하고 이런걸 조아하는거야ㅋㅋㅋㅋ원래 성인은 다들 스스로를 책임지고 보호하고 살 수 잇어ㅋㅋㅋ웃기는 사람 여튼 재밋엇던 하루. 그러고 또 해피아워보내고 집감' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='해피아워보내고 집감 솔직히 이건 오바엿다 하지만 좋앗다 하지만 오바엿다 술좀 그만먹어 정신좀 차려' metadata={'dt': Timestamp('2024-07-13 01:56:38')}
page_content='오늘 요약 재밋엇음 은근 사람만나는것도 재밋네 혼자 노는것도 물론 재밋긴한데.ㅋㅋㅋㅋㅋ수영 오리발 재밋엇음. 접영 잘해보자고~~런칭리포트 수정하는데 시간 보냇고 아이템 데이터' metadata={'dt': Timestamp('2024-07-11 23:39:17')}
page_content='아이템 데이터 공유도햇고. 아침엔ㅋㅋㅋㅋ어제 일로 오빠랑 니가 서운하네 내가 서운하네 하다가 난 읽씹 당해서 그냥 점심안먹고 잣는데 그동안 유환이는 내가 연락이 너무 안되서' metadata={'dt': Timestamp('2024-07-11 23:39:17')}
page_content='연락이 너무 안되서 걱정하는 사태 발생ㅋㅋㅋ쌤통이당 흥 근데 진짜 잘잣다. 어제 일기쓴다고 너무 늦게자서 어휴 오늘 너무 졸렷어…아침으로 나온 충무김밥먹구 식빵도 먹구~룰루.' metadata={'dt': Timestamp('2024-07-11 23:39:17')}
page_content='식빵도 먹구~룰루. 저녁은 워니랑 같이 퇴근해서 나는 멜팅피자 가는줄알앗으나 대학원3인방은 웨이팅싫어하며 다른 피자집 찾아보는데 주변엔 다른 피자집없음ㅋㅋㅋㅋ덥다고 난리,,,그래' metadata={'dt': Timestamp('2024-07-11 23:39:17')}
page_content='난리,,,그래 그럼 택시타자 해서 택시타고 갓다. 회사 얘기 잔뜩항 하루 다들 결혼하는 근황 들엇다. 다들..어느새..양재연씨도 결혼한다는 소식. 용환이만 안하네. 다들@일하는' metadata={'dt': Timestamp('2024-07-11 23:39:17')}
page_content='다들@일하는 얘기@잔뜩하고 오빠들 무슨 일하는지 물어보거 용환이가 재밋어보엿디. 김용환씨랑 공모전할때 진짜 재밋엇는데…즐거웟던 추억~.~ 공모전 마감 일주일 벼락치기 햇던 얘기' metadata={'dt': Timestamp('2024-07-11 23:39:17')}
page_content='벼락치기 햇던 얘기 코드 더러운 얘기 산책나갓다가 우리 아빠만난 얘기 발표 10준 준비햇는데 20분이엇던 얘기 심사 끝나고 엄마회사 회의실 빌려서 팀플 발표한' metadata={'dt': Timestamp('2024-07-11 23:39:17')}
page_content='빌려서 팀플 발표한 얘기ㅋㅋㅋㅋㅋㅋㅋ웃기다. 랭킹 추찬 모델링 김유환이 얘기하는 모델 반도 이해못함 휴 반성하며 공부 영심히 하기로 다짐. 먹성조은 남정네 셋이 저ㅜ피자 두판이나' metadata={'dt': Timestamp('2024-07-11 23:39:17')}
page_content='저ㅜ피자 두판이나 먹고 저거 6조각나오ㅓㅅ다고 조각마다 한번씩 더 자르는데 각자 자기몫의 자를 피자가 잇엇는데 그게 웃갸서 메인사진ㅋㅋㅋㅋㅋㅋㅋㅋ그리고 김용환의 맥주 따르기' metadata={'dt': Timestamp('2024-07-11 23:39:17')}
page_content='맥주 따르기 실력;; 즐거웟다 또보자 친구들앙' metadata={'dt': Timestamp('2024-07-11 23:39:17')}
page_content='ㅎㅏ 별개로 누님과의 만남은 즐거웠움 김유환 호감도-100 김은수 호감도+10000 누나는 대화하기 편안한 사람이라는거 너무 인정 김유환의 말에 하나도 공감하는거 같지 않은' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='같지 않은 제스처가 문득뮨득 눈에 보였으나 그게 입 밖으로, 말로 나오지 않는게 존경스러울 정도. 그 모습을 보는게 재밌었다 분명 다른 생각하시는거 같은데 반대한다는 말은' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='반대한다는 말은 안함ㅋㅋㅋㅋㅋㅋㅋㅋ신기해라..저런 스킬을 그져야해…첫인상은 목소리도 톤도 말하는 속도도 너무 직업으로서 나를 대하는 느낌의 톤이라 재맛엇음 정신과의사 처음보는거라' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='처음보는거라 약간 자꾸 종특으로 이해하게되는데 이러면 안되긴 하지만 멋졋다. 나도 저런 안정적인 말투를 가지고 싶다고 생각햇음. 그녀는 대화하는데 편안하게 해주는 사람이긴 햇다' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='사람이긴 햇다 자기 얘기를 생각보다 잘해주시고 설명도 듣기 편안하고 이해 잘되게 말씀하시고 말을 길~게하시는 경우에는 쌍괄식으로 말함.ㅋㅋㅋㅋㅋㅋㅋ오잉 이 얘기가 왜 나왓지 하는' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='왜 나왓지 하는 순간에 처음에 시작했던 주제를 끌고 와서 말해서 와 이거 나 유튜브에서 말잘하는 방법 영상에서 본거랑 똑같다고 생각했다. 그리고 그녀는 굿리스너,,,오빠의 말이' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='말이 점점 길어지는데 잘 듣고 계셨다. 근데 굿리스너인 척 하는ㄴ 날도 있다고 고뱍하셔서 인간적인 모습까지 보엿어 재밋어. 그리고 자기가 생각하는 김유환의 특징을 되게 잘' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='특징을 되게 잘 설명해주셨다. 뭐엿더라. 감정이든 충동이든 절제를 잘한다 가족한테 미주알고주알 말하는 편은 아니고 간섭받는걸 싫어하는 편이다 고집이 센편 생각이 많은편 이런저런' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='많은편 이런저런 생각이 많아서 의사결정을 하는데 웬만하면 잘못된 선택은 안하는거 같다 < 이런 신뢰를 받고 있는것도 신기했움. 이러쿵저러쿵 예전에 오빠가 설명햇던 본인이 생각하는' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='본인이 생각하는 본인의 성격과 비숫하게 말쑴하시는거 같었다. 오빠가 스스로 말해서 재밌엇던건 아빠가 뭐하자고 하는건 아빠가 주도해야하는 아빠 가정이고 나는 내가정만 주도하면 돤다고' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='주도하면 돤다고 생각하눈게 이게 무슨소리지 싶엇다. 누나도 이건 이해못하시는 듯햇음. 하지만 남자들이 남지 정신과 의사보다 여성을 선호하는거 친구들에게 고민상담을 자주 하지 않는것' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='자주 하지 않는것 의사와 환자위 관계를 엄마처럼 본다는 그런 얘기랑 남성은 여성대비 그렇게 속털어놓을 사람이 없어서 뱌우자의 역할이 그 역할이라는 거 이런 얘기도 쟈밋엇다. 근데' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='쟈밋엇다. 근데 이개 아빠가정은 아빠가 주도하고 사공아 망ㅎ으면 산우로 간다는게 뭔소리야 햡조적일 수는 잇잖아 햣눈데 오빠는 스스로 햡조작이라고 함 누님른 동의하시진 않는것' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='동의하시진 않는것 같앗다. 간섭받는걸 싫어하는 편이라는건 처음 알게돤거긴 하네…간섭할일이없긴 햇지만. 알아서 잘하면 간섭할일 없으니 노상관인가? 고집이 센편은 알겟음. 오늘' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='알겟음. 오늘 네비게이션 그냥 진행시켜버린것만우로도 알겟는데 생각해모면 구런느낌의 일들이 종종잇엇다. 여튼 누나가 생각하는 오빠 특징들 듣고 거기에 오빠가 스스로 설명하는것도' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='스스로 설명하는것도 쟈맛엇음. 내얘기도 종종햣는데 누나가 생각하는 나는 정리를 잘하고 규칙적인 삶살고 씩씩하고 현실적이지만 도전적인(말만잘하는)으로 평가내려줫는데 웃겻다 나 정신' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='웃겻다 나 정신 분석당하는거 아니야 해ㅛ는데 진짜 당햣음 근데 무서운건 아니고 재밋어. 오빠는 내가 정리하고 기록하고 이런 일들을 아주 높개 평가해줫다. 근데 그냥 기억이 안나서' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='그냥 기억이 안나서 할 수 밖에 없는거 뿐이야. 누나는 오빠가 나를 엄청 좋아하는거 같다고 이전에 사귄 여자친구들한테 이렇게 잘해주는지 몰랏다까지 말하랴고 하시는거 같앗고 유환이가' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='같앗고 유환이가 사랑에 빠졋다 진짜 좋아하는거 갗다 정도는 얘기하셧눔 그러고 헤어질때쯤 어머니 환갑 식당 유환아 너가 가봣다며 라고 이야기하셧엇는데 유환이가 잠깐 당황햇다가 응' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='잠깐 당황햇다가 응 아니 안가봣오라고 햣는데 오빠가 그게 신경쑤엿는지 누님가시고 나서 나한테 추가 설명함. 이전하기 전엔 가봣는데 이전하고 나서는 안가봣다고 누구랑 갓겟어' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='누구랑 갓겟어 전여친이랑 갔겠지 하지만 별로 신경ㅁ수고 싶지않아서 그냥 얼갯다고 햇다. 흥미로운 경험이엇어…욘두보다 훨재밌엇음 음식도 너무 맛있었고. 누님 만나는거 너무 즐거웟고' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='너무 즐거웟고 스트레스 받은게 민망할 지경으로 재밋엇고 또보고싶은 마음이 들어서 너무 신기햇던 만남이엇다. 유환이 다른 가족준들고 기회가 되면 볼일이@잇을까 근데 그때도 똑같이' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='근데 그때도 똑같이 이렇게스트레스@받을 생각하니 굳이 미리 받을 필요잇나 싶어 걍혼하면 보면되지 그냥 살자 흘러가는대로 걍 잘 모루갯음. 이젠 진짜 자야겟다 낼 수영 못갈듯' metadata={'dt': Timestamp('2024-07-11 00:11:55')}
page_content='정말 힘들었던 오늘 하루. 아침에 진짜 난리도아니었다. 수영은 재밌었음. 집에서 나갈준비하는데 오랜만에 출근날 화장도 하고 옷 뭐입읗지 못정해서ㅋㅋㅋ계속 고민하다가 옷 하나 그냥' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='옷 하나 그냥 싸들고 나왔다. 양말까지ㅋㅋㅋ나도 내 스스로가 어이없어…오빠 누님 만나는날 출근해ㅆ는데 옷이 맘에 안들어서 혹시 갈아입고 싶을까봐 옷을 싸서 출근한게…그러고' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='출근한게…그러고 지하철-카드놓고옴-집-엘베놓침-땀미침-지하철-카드없음-돌아감-가는길에찾음-출근 루트를 겪고 진짜 눈물날뻔햇다. 정말이지 올해 가장 불행한 하루였어 멘탈 털린채로' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='멘탈 털린채로 출근하고 회사에서 샤워하고 나서 좀 정신 차리고…자리에 워니랑 몰리가 두고간 선물들이 약간 기분 좋았다. 출근 하는 길에 오빠한테 엄청나게 징징거렸다 하지만 올해' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='하지만 올해 가장 불행한 순간이었어…결국 반반차도 썼다 내 소중한 반반차…일은 그냥저냥 했음.

내가 반반차쓴거에 맞춰서 오바가 데릴러와줘서 명동으로 이동햇다 나는 7시반에 우리' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='나는 7시반에 우리 약속이니까 오빠랑 좀 꽁냥대다가 저녁 맛있는거 먹으면 되겟다 했는데 갑자기 오빠가 누나 픽업가자고…ㅋㅋㅋㅋㅋㅋ내가 싫다고 다섯번 넘ㄱㅔ 말했는데 오빠가' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='말했는데 오빠가 임산부니까 데릴러 가는게 좋겠다고 말하고 네비에 찍어버렸다. 기분 나쁜 포인트 1. 누나를 일찍 만날 수 있는 상황을 미리 고지해주지 않음. 내 마음의 준비 없어서' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='마음의 준비 없어서 스트레스극심 2. 내 반반차에 오빠가 안고있자고 말해놓고 약속 안지킴 나의 기대감 와장창 3. 이미 여러번 거절했는데 그냥 네비찍고 가는걸로 혼자 결정하며 내' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='혼자 결정하며 내 의견은 그냥 무시 4. 임산부임을 어필하며 거절한 나는ㅋㅋㅋ파렴치한으로 만들어 수동공격함 내가 극대노하는거 같으니 그제서야 네비를 취소하네 마네 실랑이 벌얏다.' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='실랑이 벌얏다. 이럴거였으면 나는 그냥 혼자 지하철타고 명동가서 기다리며 마음준비하는게 더 나앗을지도라고 생각함 근데 그건 안된대 왜냐 그럼 오빠 마음이 안좋으니까 근데 나는' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='근데 나는 진심으류 짜증났다 상황적으로 모시러가는거가 베스트인거 알겠는데 그럼 혼자 가든가 아님 미리 말하든가 왜 나에겐 선택권 주지 않지? 임산부 누님 걱정되는거면 나에게' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='걱정되는거면 나에게 양해구해서 가라고…물론 당일에 갑자기 말고 미리.미리 생각 못했다고 하더라도 내 의견 이렇게 싸그리 무시하고 가는 것도 잘한건 아니잖아. 내가 부담가지고' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='내가 부담가지고 힘들어하는거 알고있으면서 ㅋㅋㅋㅋ집가는것도 혼자가고싶다고까지 말했었는데 내가 얼마나 스트레스 받고 있는지 배려1도 안하고 자기 맘대로 막 결정하는거 진짜 실망인' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='진짜 실망인 수준이엇다. 의견을 묻고 대답을 했으면 받아들이기라도 하든가 아님 설득을 하거나 달래거나 뭐 하나라도 하고 결정해야할거 아니야? 밉다고 순화해서 말하니까 멘탈 털린다고' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='멘탈 털린다고 피해자 코스프레함 어쩌라고…밉기만 한줄 알아? 참나…근데 어쨌든 누나 만나는 일정은 다가오고 있고 전화해서 가겟다고 말까지 했고 가는 걸로 결정했는데 분위기 망한' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='분위기 망한 채로 만남을 진행할 수 없어서 일단 넘어갔다. 근데 다시 복기하니까 또열받음 다신 이런 경험하고 싶지 않다 다섯번 거절햇는데 네비찍지 않앗냐고 내가 허락한게 진짜' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='내가 허락한게 진짜 허락같냐고 너가 강요한거라고 돌려말했는데 그럼 세번 더 물어보겟다는건 말이야 방구야 싫다고 이미 의사표현을 했는데 왜 세번이나 더 거절해야되는데..진짜' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='으..

그거랑 별개로 누나와의 만남은 즐거웠음.

구러고 집와서 하이라이트 누나랑 만나게하려고 한 이유가 머냐고 물엇을때 누나를 통해 나를 알앗우면 하는 마음40 누나랑' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='마음40 누나랑 안면트기20이래서 나머지 40은 뭐냐니까 별생각없음이라고. 별생각 없음으로 나에게 이런 스트래스를 줬단 말이야? 내가 얼마나 큰 마음을 먹고 나간건데 또 열받아서' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='또 열받아서 갈궜더니 뭔 답정너한ㅌㅔ 말하는거처럼 결혼을 얌두에 둔 첫발걸음이라고 말 바뀨ㅓㅅ는데 도대체 어딜 봐서 별생각없움이 결혼 염두 발걸음이야 그러면거 윤영이 어렵다????' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='어렵다???? 내가 예민하게 군다는거지 이거 지금 이게 혹시 고부갈등의 시초일까? 내가 어떻개 했으면 화가 안났을까 나의 힘든 결정을 알아줬으면 좋겠는데 그부뷴을 내가 과도하게' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='내가 과도하게 요구했나 근데 안알아쥴고면 이제 이런 결정 안할거야 하여간 진짜 너무너무너무 별로였다. 진심 별로였음…' metadata={'dt': Timestamp('2024-07-11 00:11:44')}
page_content='오늘 진짜 별일@다잇엇다 웃기는 하루. 아침엔 행크한테 연락할생각에 스트레스 만땅에 정말 컨디션도 안좋고 슬프고 외면하고싶고 반차내고 집가고싶엇다. 나는 행크 고민에서 이제' metadata={'dt': Timestamp('2024-07-10 00:43:34')}

- 지정한 separators 리스트를 순차적으로 시도하며 주어진 문서를 분할합니다.
- 청크가 충분히 작아질 때까지 순서대로 분할을 시도합니다. 기본 목록은 ["\n\n", "\n", " ", ""]입니다.
- 이는 일반적으로 의미적으로 가장 연관성이 강한 텍스트 조각인 것처럼 보이는 모든 단락(그리고 문장, 단어)을 가능한 한 길게 유지하려는 효과가 있습니다.

In [17]:
# recursive_text_splitter 에 기본 지정된 separators 를 확인합니다.
recursive_text_splitter._separators

['\n\n', '\n', ' ', '']

In [41]:
loader = DataFrameLoader(df_nodup, page_content_column="title")

# splitter 를 정의합니다.
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000,
                                                chunk_overlap=50,
                                                length_function=len,
                                                is_separator_regex=False,)

# 문서를 로드시 바로 분할까지 수행합니다.
split_docs = loader.load_and_split(text_splitter=text_splitter)
print(f"문서의 수: {len(docs)}")
docs[14].page_content[:500]

문서의 수: 1449

'엽떡데이-저스틴 왜 잔을 안들고오새용?🙂 엽떳 과식하고 저녁은 굶어버려 퇴근해서 낼 도시락준비하고 누워서 쉬엇다. 목이 넘 간지러'

### Semantic Similarity

의미적 유사성을 기준으로 텍스트를 분할합니다.

출처: [Greg Kamradt’s Notebook](https://github.com/FullStackRetrieval-com/RetrievalTutorials/blob/main/5_Levels_Of_Text_Splitting.ipynb)

높은 수준(high level)에서 문장으로 분할한 다음 3개 문장으로 그룹화한 다음 임베딩 공간에서 유사한 문장을 병합하는 방식입니다.

In [ ]:
# 최신 버전으로 업데이트합니다.
# !pip install -U langchain langchain_experimental -q

In [2]:
from langchain_experimental.text_splitter import SemanticChunker
from langchain_openai.embeddings import OpenAIEmbeddings

# SemanticChunker 를 생성합니다.
semantic_text_splitter = SemanticChunker(OpenAIEmbeddings(), add_start_index=True)

In [1]:
# chain of density 논문의 일부 내용을 불러옵니다
for sent in semantic_text_splitter.split_text(docs):
    print(sent)
    print("===" * 20)

NameError: name 'semantic_text_splitter' is not defined

In [ ]:
# chain of density 논문의 일부 내용을 불러옵니다
with open("data/chain-of-density.txt", "r") as f:
    text = f.read()

for sent in semantic_text_splitter.split_text(text):
    print(sent)
    print("===" * 20)

In [ ]:
from langchain_community.vectorstores import FAISS
from langchain_openai.embeddings import OpenAIEmbeddings

# 단계 3: 임베딩 & 벡터스토어 생성(Create Vectorstore)
# 벡터스토어를 생성합니다.
vectorstore = FAISS.from_documents(documents=splits, embedding=OpenAIEmbeddings())

## 3 단계: 임베딩

참고: https://python.langchain.com/docs/integrations/text_embedding

### 유료 과금 임베딩(OpenAI)

In [ ]:
from langchain_community.vectorstores import FAISS
from langchain_openai.embeddings import OpenAIEmbeddings

# 단계 3: 임베딩 & 벡터스토어 생성(Create Vectorstore)
# 벡터스토어를 생성합니다.
vectorstore = FAISS.from_documents(documents=splits, embedding=OpenAIEmbeddings())

다음은 `OpenAI` 의 지원되는 Embedding 모델들의 목록입니다.

- 기본 값은 `text-embeding-ada-002` 입니다.

| MODEL                  | ROUGH PAGES PER DOLLAR | EXAMPLE PERFORMANCE ON MTEB EVAL |
| ---------------------- | ---------------------- | -------------------------------- |
| text-embedding-3-small | 62,500                 | 62.3%                            |
| text-embedding-3-large | 9,615                  | 64.6%                            |
| text-embedding-ada-002 | 12,500                 | 61.0%                            |

In [ ]:
vectorstore = FAISS.from_documents(
    documents=splits, embedding=OpenAIEmbeddings(model="text-embedding-3-small")
)

### 무료 Open Source 기반 임베딩

In [26]:
from langchain_community.embeddings import HuggingFaceBgeEmbeddings

# 단계 3: 임베딩 & 벡터스토어 생성(Create Vectorstore)
# 벡터스토어를 생성합니다.
vectorstore = FAISS.from_documents(
    documents=split_docs, embedding=HuggingFaceBgeEmbeddings()
)

model.safetensors:  59%|#####9    | 797M/1.34G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

In [ ]:
# !pip install fastembed -q

In [ ]:
from langchain_community.embeddings.fastembed import FastEmbedEmbeddings

vectorstore = FAISS.from_documents(documents=splits, embedding=FastEmbedEmbeddings())

## 4단계: 벡터스토어 생성(Create Vectorstore)

In [ ]:
from langchain_community.vectorstores import FAISS

# FAISS DB 적용
vectorstore = FAISS.from_documents(documents=splits, embedding=OpenAIEmbeddings())

In [ ]:
from langchain_community.vectorstores import Chroma

# Chroma DB 적용
vectorstore = Chroma.from_documents(documents=splits, embedding=OpenAIEmbeddings())

## 5단계: Retriever 생성

리트리버는 구조화되지 않은 쿼리가 주어지면 문서를 반환하는 인터페이스입니다.

리트리버는 문서를 저장할 필요 없이 문서를 반환(또는 검색)하기만 합니다.

- [공식 도큐먼트](https://python.langchain.com/docs/modules/data_connection/retrievers/)

생성된 VectorStore 에 `as_retriver()` 로 가져와서 **Retriever** 를 생성합니다.

### 유사도 기반 검색

- 기본값은 코사인 유사도인 `similarity` 가 적용되어 있습니다.

In [42]:
query = "2022년도엔 대체로 무슨일이 있었어?"

retriever = vectorstore.as_retriever(search_type="similarity")
search_result = retriever.get_relevant_documents(query)
print(search_result)

[Document(metadata={'dt': Timestamp('2022-12-31 00:34:25')}, page_content='이얏호 2022마지막 출근-잠실에서 술먹기'), Document(metadata={'dt': Timestamp('2023-12-31 18:35:00')}, page_content='아침에 딩굴대다가 전부치는 하루 갈비구워먹을거 약간 기대햇는데 고모가 해오신대서 우린 안해도됐다 근데 우리가 하는 갈비가 더 맛잇는데..ㅠ.ㅠ그래도 대충 네시쯤 끝낫으니까 금방끝난듯 낼 가면 새뱃돈 주시나? 내가 사촌들 중에 젤 짧게 받앗어 너무 손해야 문석오빠는 35까지 받앗는데 나만 못받아 나는 줘야지!! 이불 바꾸고 쉬니까 행복하다 배부르고 등따신 2023 마지막날 아 정리하는@릴스@만들어야겟다'), Document(metadata={'dt': Timestamp('2023-12-27 04:10:19')}, page_content='좋아 도대체 뮤슨일일까? 나에게 이런 방탕한 삶이 허락되는 날이 오다니 아무도 허락안햇지만 그냥 나혼자 폭주하기 내가 허락하면 됐지 뭐,,진짜 근데 너무너무 방탕하고 오빠가 너무 잘해줘서 거의 목욕시중을 들어주는 수준인데 몸 둘바를 모르겠기도 하고 근데 또 너무 좋고 야하고 근데 또 못 움직이겟는 것도 맞아ㅋㅋㅋ체력이..자꾸 바닥나는데 오빠가 마사지해주고 목욕시켜줘서 강제로 끌어올리고 난 아 다 회복됐나보다^^하고 착각하고 다시 뽈뽈거리다가 체력 바닥나고 오빠가 다시 강제로 끌어올리고ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ이 순환이 너무 웃기다. 행복하고 즐거워ㅋㅋㅋ운동 열심히해야겠다..!!'), Document(metadata={'dt': Timestamp('2021-06-02 21:45:02')}, page_content='대학원 도서관의 하루. 거기서 뭘했는진 모르겠지만?? 그냥 공간이 예뻐서 기분이 좋았다. 낼 면접인데 왕창 스트레스 받다가 또 그냥 아 엔씨 구경하고 와야지..하고 그냥 맘놓기. 난 쓰레기같은 삶살지만 조금이라도 덜 쓰레기같아 보이도록 조금이나마..몰라..아 씨엔에스 면접이 진짜 편햇는데..몰라..원래는 걍 플젝 얘기하고 싶었는데 논문 얘기하기로 바꿨다 잘모르는거 기술 질문 들어올바에야 그냥…디펜스 준비겸. 용환오빠 오늘 디펜스해서 통과했다는데 부럽다 척척석사 축하 나도 낼모레면 척척석사다')]

`similarity_score_threshold` 는 유사도 기반 검색에서 `score_threshold` 이상인 결과만 반환합니다.

In [ ]:
query = "회사의 저출생 정책이 뭐야?"

retriever = vectorstore.as_retriever(
    search_type="similarity_score_threshold", search_kwargs={"score_threshold": 0.8}
)
search_result = retriever.get_relevant_documents(query)
print(search_result)

`maximum marginal search result` 를 사용하여 검색합니다.

In [ ]:
query = "회사의 저출생 정책이 뭐야?"

retriever = vectorstore.as_retriever(search_type="mmr", search_kwargs={"k": 2})
search_result = retriever.get_relevant_documents(query)
print(search_result)

### 다양한 쿼리 생성

In [28]:
from langchain.retrievers.multi_query import MultiQueryRetriever
from langchain_openai import ChatOpenAI

query = "22년도엔 무슨일이 있었어?"

llm = ChatOpenAI(temperature=0, model="gpt-3.5-turbo")

retriever_from_llm = MultiQueryRetriever.from_llm(
    retriever=vectorstore.as_retriever(), llm=llm
)

In [ ]:
# Set logging for the queries
import logging

logging.basicConfig()
logging.getLogger("langchain.retrievers.multi_query").setLevel(logging.INFO)

In [ ]:
unique_docs = retriever_from_llm.get_relevant_documents(query=question)
len(unique_docs)

### Ensemble Retriever

In [44]:
from langchain.retrievers import BM25Retriever, EnsembleRetriever
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings

In [46]:
doc_list = [
    "난 오늘 많이 먹어서 배가 정말 부르다",
    "떠나는 저 배가 오늘 마지막 배인가요?",
    "내가 제일 좋아하는 과일들은 배, 사과, 키워, 수박 입니다.",
]

# initialize the bm25 retriever and faiss retriever
bm25_retriever = BM25Retriever.from_texts(doc_list)
bm25_retriever.k = 2

faiss_vectorstore = FAISS.from_texts(doc_list, OpenAIEmbeddings())
faiss_retriever = faiss_vectorstore.as_retriever(search_kwargs={"k": 2})

# initialize the ensemble retriever
ensemble_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, faiss_retriever], weights=[0.5, 0.5]
)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [47]:
def pretty_print(docs):
    for i, doc in enumerate(docs):
        print(f"[{i+1}] {doc.page_content}")

In [48]:
sample_query = "나 요즘 배에 정말 살이 많이 쪘어..."
print(f"[Query]\n{sample_query}\n")
relevant_docs = bm25_retriever.get_relevant_documents(sample_query)
print("[BM25 Retriever]")
pretty_print(relevant_docs)
print("===" * 20)
relevant_docs = faiss_retriever.get_relevant_documents(sample_query)
print("[FAISS Retriever]")
pretty_print(relevant_docs)
print("===" * 20)
relevant_docs = ensemble_retriever.get_relevant_documents(sample_query)
print("[Ensemble Retriever]")
pretty_print(relevant_docs)

[Query]
나 요즘 배에 정말 살이 많이 쪘어...

[BM25 Retriever]
[1] 난 오늘 많이 먹어서 배가 정말 부르다
[2] 내가 제일 좋아하는 과일들은 배, 사과, 키워, 수박 입니다.
============================================================
[FAISS Retriever]
[1] 난 오늘 많이 먹어서 배가 정말 부르다
[2] 떠나는 저 배가 오늘 마지막 배인가요?
============================================================
[Ensemble Retriever]
[1] 난 오늘 많이 먹어서 배가 정말 부르다
[2] 내가 제일 좋아하는 과일들은 배, 사과, 키워, 수박 입니다.
[3] 떠나는 저 배가 오늘 마지막 배인가요?

In [49]:
sample_query = "바다 위에 떠다니는 배들이 많다"
print(f"[Query]\n{sample_query}\n")
relevant_docs = bm25_retriever.get_relevant_documents(sample_query)
print("[BM25 Retriever]")
pretty_print(relevant_docs)
print("===" * 20)
relevant_docs = faiss_retriever.get_relevant_documents(sample_query)
print("[FAISS Retriever]")
pretty_print(relevant_docs)
print("===" * 20)
relevant_docs = ensemble_retriever.get_relevant_documents(sample_query)
print("[Ensemble Retriever]")
pretty_print(relevant_docs)

[Query]
바다 위에 떠다니는 배들이 많다

[BM25 Retriever]
[1] 내가 제일 좋아하는 과일들은 배, 사과, 키워, 수박 입니다.
[2] 떠나는 저 배가 오늘 마지막 배인가요?
============================================================
[FAISS Retriever]
[1] 난 오늘 많이 먹어서 배가 정말 부르다
[2] 떠나는 저 배가 오늘 마지막 배인가요?
============================================================
[Ensemble Retriever]
[1] 떠나는 저 배가 오늘 마지막 배인가요?
[2] 내가 제일 좋아하는 과일들은 배, 사과, 키워, 수박 입니다.
[3] 난 오늘 많이 먹어서 배가 정말 부르다

In [50]:
sample_query = "ships"
print(f"[Query]\n{sample_query}\n")
relevant_docs = bm25_retriever.get_relevant_documents(sample_query)
print("[BM25 Retriever]")
pretty_print(relevant_docs)
print("===" * 20)
relevant_docs = faiss_retriever.get_relevant_documents(sample_query)
print("[FAISS Retriever]")
pretty_print(relevant_docs)
print("===" * 20)
relevant_docs = ensemble_retriever.get_relevant_documents(sample_query)
print("[Ensemble Retriever]")
pretty_print(relevant_docs)

[Query]
ships

[BM25 Retriever]
[1] 내가 제일 좋아하는 과일들은 배, 사과, 키워, 수박 입니다.
[2] 떠나는 저 배가 오늘 마지막 배인가요?
============================================================
[FAISS Retriever]
[1] 떠나는 저 배가 오늘 마지막 배인가요?
[2] 내가 제일 좋아하는 과일들은 배, 사과, 키워, 수박 입니다.
============================================================
[Ensemble Retriever]
[1] 내가 제일 좋아하는 과일들은 배, 사과, 키워, 수박 입니다.
[2] 떠나는 저 배가 오늘 마지막 배인가요?

In [ ]:
sample_query = "pear"
print(f"[Query]\n{sample_query}\n")
relevant_docs = bm25_retriever.get_relevant_documents(sample_query)
print("[BM25 Retriever]")
pretty_print(relevant_docs)
print("===" * 20)
relevant_docs = faiss_retriever.get_relevant_documents(sample_query)
print("[FAISS Retriever]")
pretty_print(relevant_docs)
print("===" * 20)
relevant_docs = ensemble_retriever.get_relevant_documents(sample_query)
print("[Ensemble Retriever]")
pretty_print(relevant_docs)

## 6단계: 프롬프트 생성(Create Prompt)

프롬프트 엔지니어링은 주어진 데이터(`context`)를 토대로 우리가 원하는 결과를 도출할 때 중요한 역할을 합니다.

[TIP1]

1. 만약, `retriever` 에서 도출한 결과에서 중요한 정보가 누락된다면 `retriever` 의 로직을 수정해야 합니다.
2. 만약, `retriever` 에서 도출한 결과가 많은 정보를 포함하고 있지만, `llm` 이 그 중에서 중요한 정보를 찾지 못한거나 원하는 형태로 출력하지 않는다면 프롬프트를 수정해야 합니다.

[TIP2]

1. LangSmith 의 **hub** 에는 검증된 프롬프트가 많이 업로드 되어 있습니다.
2. 검증된 프롬프트를 활용하거나 약간 수정한다면 비용과 시간을 절약할 수 있습니다.

- https://smith.langchain.com/hub/search?q=rag

In [ ]:
from langchain import hub

In [51]:
prompt = hub.pull("rlm/rag-prompt")
prompt

ChatPromptTemplate(input_variables=['context', 'question'], metadata={'lc_hub_owner': 'rlm', 'lc_hub_repo': 'rag-prompt', 'lc_hub_commit_hash': '50442af133e61576e74536c6556cefe1fac147cad032f4377b60c436e6cdcb6e'}, messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['context', 'question'], template="You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise.\nQuestion: {question} \nContext: {context} \nAnswer:"))])

## 7단계: 언어모델 생성(Create LLM)

OpenAI 모델 중 하나를 선택합니다.

- `gpt-3.5-turbo` : OpenAI의 GPT-3.5-turbo 모델
- `gpt-4-turbo-preview` : OpenAI의 GPT-4-turbo-preview 모델

자세한 비용 체계는 [OpenAI API 모델 리스트 / 요금표](https://teddylee777.github.io/openai/openai-models/)에서 확인할 수 있습니다.

In [ ]:
from langchain_openai import ChatOpenAI

model = ChatOpenAI(temperature=0, model="gpt-3.5-turbo")

다음의 방식으로 토큰 사용량을 확인할 수 있습니다.

In [ ]:
from langchain.callbacks import get_openai_callback

with get_openai_callback() as cb:
    result = model.invoke("대한민국의 수도는 어디인가요?")
print(cb)

HuggingFace 에 업로드 되어 있는 오픈소스 모델을 손쉽게 다운로드 받아 사용할 수 있습니다.

아래의 리더보드에서 날마다 성능을 개선하는 오픈소스 리더보드를 확인할 수 있습니다.

- [HuggingFace LLM Leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard)

In [ ]:
# HuggingFaceHub 객체 생성
from langchain.llms import HuggingFaceHub

repo_id = "google/flan-t5-xxl"

t5_model = HuggingFaceHub(
    repo_id=repo_id, model_kwargs={"temperature": 0.1, "max_length": 512}
)

In [ ]:
t5_model.invoke("Where is the capital of South Korea?")

## RAG 템플릿 실험

In [ ]:
# 단계 1: 문서 로드(Load Documents)
# 문서를 로드하고, 청크로 나누고, 인덱싱합니다.
from langchain.document_loaders import PyPDFLoader

# PDF 파일 로드. 파일의 경로 입력
file_path = "data/SPRI_AI_Brief_2023년12월호_F.pdf"
loader = PyPDFLoader(file_path=file_path)

# 단계 2: 문서 분할(Split Documents)
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=50)

split_docs = loader.load_and_split(text_splitter=text_splitter)

# 단계 3, 4: 임베딩 & 벡터스토어 생성(Create Vectorstore)
# 벡터스토어를 생성합니다.
# vectorstore = FAISS.from_documents(documents=splits, embedding=OpenAIEmbeddings())
vectorstore = FAISS.load_local('../db/faiss', HuggingFaceBgeEmbeddings(), allow_dangerous_deserialization=True)

# 단계 5: 리트리버 생성(Create Retriever)
# 사용자의 질문(query) 에 부합하는 문서를 검색합니다.

# 유사도 높은 K 개의 문서를 검색합니다.
k = 3

# (Sparse) bm25 retriever and (Dense) faiss retriever 를 초기화 합니다.
bm25_retriever = BM25Retriever.from_documents(split_docs)
bm25_retriever.k = k

faiss_vectorstore = FAISS.from_documents(split_docs, OpenAIEmbeddings())
faiss_retriever = faiss_vectorstore.as_retriever(search_kwargs={"k": k})

# initialize the ensemble retriever
ensemble_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, faiss_retriever], weights=[0.5, 0.5]
)

# 단계 6: 프롬프트 생성(Create Prompt)
# 프롬프트를 생성합니다.
prompt = hub.pull("rlm/rag-prompt")

# 단계 7: 언어모델 생성(Create LLM)
# 모델(LLM) 을 생성합니다.
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)


def format_docs(docs):
    # 검색한 문서 결과를 하나의 문단으로 합쳐줍니다.
    return "\n\n".join(doc.page_content for doc in docs)


# 단계 8: 체인 생성(Create Chain)
rag_chain = (
    {"context": ensemble_retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

# 결과 출력
print(f"PDF Path: {file_path}")
print(f"문서의 수: {len(docs)}")
print("===" * 20)
print(f"[HUMAN]\n{question}\n")
print(f"[AI]\n{response}")

> 문서: data/SPRI_AI_Brief_2023년12월호\_F.pdf (페이지 10)

- LangSmith: https://smith.langchain.com/public/4449e744-f0a0-42d2-a3df-855bd7f41652/r

In [53]:
# 단계 8: 체인 실행(Run Chain)
# 문서에 대한 질의를 입력하고, 답변을 출력합니다.
question = "삼성 가우스에 대해 설명해주세요"
response = rag_chain.invoke(question)
print(response)

NameError: name 'rag_chain' is not defined

> 문서: data/SPRI_AI_Brief_2023년12월호\_F.pdf (페이지 12)

- LangSmith: https://smith.langchain.com/public/2b2913c9-6b9c-4a19-bb16-dc2256e2fdbf/r

In [ ]:
# 단계 8: 체인 실행(Run Chain)
# 문서에 대한 질의를 입력하고, 답변을 출력합니다.
question = "미래의 AI 소프트웨어 매출 전망은 어떻게 되나요?"
response = rag_chain.invoke(question)
print(response)

> 문서: data/SPRI_AI_Brief_2023년12월호\_F.pdf (페이지 14)

- LangSmith: https://smith.langchain.com/public/17ef6df2-b012-4f8e-b0a8-62894d82c097/r

In [ ]:
# 단계 8: 체인 실행(Run Chain)
# 문서에 대한 질의를 입력하고, 답변을 출력합니다.
question = "YouTube 가 2024년에 의무화 한 것은 무엇인가요?"
response = rag_chain.invoke(question)
print(response)

In [52]:
response

NameError: name 'response' is not defined